apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aa5g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aa5g
    app.kubernetes.io/part-of: ci1t-830-0007-app
  name: devfile-sample-aa5g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aa5g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aa5g
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0007-tenant/ci1t-830-0007-app/devfile-sample-aa5g@sha256:b0a7e92eae91e10ec909308bf02cbe8023ada5ca4c4e0bb3d342e707fa1b4b20
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
